theme = "awesome-identity"
baseURL = "https://junedkazi.com"
title = "Juned Kazi - Engineering Leader"
# Enable to turn relative URLs into absolute
canonifyURLs = true
publishDir = "docs"

## Profile Configurations
[params.profile]
  portrait = "/images/jak-photo.jpg"
  firstname = "Juned"
  lastname = "Kazi"
  title = "Engineering Manager, Affirm Inc"
  bio = """Juned Kazi brings over 10 years of experience leading, contributing to, and growing engineering organizations.
  He is currently working as an Engineering Manager at [Affirm](https://www.affirm.com/) managing and mentoring resources on the partner platform team. 
  """

## Contacts Configurations
[params.contacts]
  github = "junedkazi"
  twitter = "junedkazi"
  linkedin = "junedkazi"
  keybase = "junedkazi"

## Footer Configurations
[params.footer]
  copyright = "© 2022 Juned Kazi. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = false
